---
# =============================================================================
# DOCKER INSTALLATION (doit être en premier)
# =============================================================================

- name: Install required dependencies for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
    state: present
    update_cache: yes

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present
    update_cache: yes  # Important : met à jour le cache après l'ajout du repo

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Wait for Docker to be ready
  wait_for:
    path: /var/run/docker.sock
    state: present
    timeout: 30

- name: Verify Docker installation
  command: docker --version
  register: docker_version
  changed_when: false

- name: Verify Docker Compose installation
  command: docker compose version
  register: compose_version
  changed_when: false
  failed_when: compose_version.rc != 0  # Doit échouer si docker compose n'est pas disponible

- name: Show Docker version
  debug:
    msg: "Docker version: {{ docker_version.stdout }}"

- name: Show Docker Compose version
  debug:
    msg: "Docker Compose version: {{ compose_version.stdout }}"

# =============================================================================
# TÂCHES MONITORING (après l'installation de Docker)
# =============================================================================

- name: Install necessary dependencies for monitoring
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Create monitoring-stack directory
  file:
    path: /opt/monitoring-stack
    state: directory
    mode: '0755'

- name: Deploy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: 'monitoring-compose.yml', dest: '/opt/monitoring-stack/docker-compose.yml' }
    - { src: 'prometheus.yml', dest: '/opt/monitoring-stack/prometheus.yml' }

- name: Deploy Monitoring with Docker Compose v2
  community.docker.docker_compose_v2:
    project_src: /opt/monitoring-stack
    state: present