---
# Install required dependencies for Docker
- name: Install required dependencies for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes  # Important : mettre à jour le cache

# Add Docker's official GPG key
- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# Add Docker repository
- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present
    update_cache: yes  # Mettre à jour le cache après l'ajout du repo

# Install Docker
- name: Install Docker
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

# Start and enable Docker service
- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

# Install Docker Compose Plugin (integrated with Docker)
- name: Install Docker Compose Plugin
  apt:
    name: docker-compose-plugin
    state: present

# Add user to docker group to avoid sudo for docker commands
- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

# Reset SSH connection to apply group changes
- name: Reset connection to apply group changes
  meta: reset_connection

# Verify Docker installation
- name: Verify Docker installation
  command: docker --version
  register: docker_version
  changed_when: false

# Verify Docker Compose installation
- name: Verify Docker Compose installation
  command: docker compose version
  register: compose_version
  changed_when: false

# Test Docker socket access
- name: Test Docker socket access
  command: docker ps
  register: docker_test
  changed_when: false
  failed_when: false  # Ne pas échouer si le test rate

# Show Docker version
- name: Show Docker version
  debug:
    msg: "Docker version: {{ docker_version.stdout }}"
    
# Show Docker Compose version
- name: Show Docker Compose version
  debug:
    msg: "Docker Compose version: {{ compose_version.stdout }}"

# Show Docker access test result
- name: Show Docker access test result
  debug:
    msg: "Docker access: {{ 'SUCCESS' if docker_test.rc == 0 else 'Using sudo fallback for this session' }}"