name: frontend-app-stack

# Define services
services:
  frontend-app:
    image: siwart8/front-session13
    container_name: frontend-app  # Set a custom name for the container
    ports:
      - '3000:80'  # Map port 3000 on the host to port 80 in the container
    networks:
      - frontend-app-network  # Connect to the defined network

